apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhoai-chatbot-sample-app 
  janus-idp.io/tekton: rhoai-chatbot-sample-app
  backstage.io/kubernetes-id: rhoai-chatbot-sample-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhoai-chatbot-sample-app
resources: 
- application-dev.yaml