apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhoai-chatbot-sample-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhoai-chatbot-sample-app 
  name: rhoai-chatbot-sample-app
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhoai-chatbot-sample-app 
    weight: 100 
  wildcardPolicy: None
