apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhoai-chatbot-sample-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhoai-chatbot-sample-app 
  name: rhoai-chatbot-sample-app
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rhoai-chatbot-sample-app 
